name: "csteach488"
subname: "An Introduction to Game Design and Development"
description: "a collection of resources for COMP 488..."

url: "http://localhost:4000"

paginate: 10

markdown: kramdown
permalink: "/:categories/:title"
highlighter: rouge

excerpt_separator: <!--more-->

collections:
  library:
    output: true
  indices:
    output: true

gems:
  - jekyll-sitemap
